package Interface;

import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class BanSach extends javax.swing.JInternalFrame {

    /**
     * Creates new form Bill
     */
    
    double firstnum;
    double secondnum;
    double result;
    String operations;
    
    double [] i = new double [5];
    
    double Dollar_Brunei = 16959.65;
    double Dollar_Singapore = 16705.99;
    double Riel = 5.8;
    double Kip = 2.7;
    double Indian_rupee = 333.79;
    double Philippine_peso = 433.37;
    double Baht = 728.26;
    double CNY = 3370.23;
    double JPY = 20000;
    double USD = 23255.81; //1 usd = 25000vnd
    double GBP = 29466.97;
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    public BanSach() {
        initComponents();
        conn = DBConnect.connect();
        ButtonGroup bg = new ButtonGroup();
        bg.add(cbxvip);
        bg.add(cbxnomal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtnamecustomer = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        date_of_sale = new com.toedter.calendar.JDateChooser();
        txtcustomertype = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        cbxvip = new javax.swing.JCheckBox();
        cbxnomal = new javax.swing.JCheckBox();
        cmbcurrency = new javax.swing.JComboBox();
        txtconvert = new javax.swing.JTextField();
        lblconvert = new javax.swing.JTextField();
        btnconvert = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        btntotal = new javax.swing.JButton();
        lbldiscount = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        btnreceipt = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jtxtDisplay = new javax.swing.JTextField();
        jBtnDelete = new javax.swing.JButton();
        jBtn10 = new javax.swing.JButton();
        jBtnAddition = new javax.swing.JButton();
        jBtn14 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtnSubtraction = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn18Multiplication = new javax.swing.JButton();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtnDivision = new javax.swing.JButton();
        jBtn0 = new javax.swing.JButton();
        jBtncomma = new javax.swing.JButton();
        jBtnEqual = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtbillcopy = new javax.swing.JScrollPane();
        txtbill = new javax.swing.JTextArea();
        btnreset = new javax.swing.JButton();
        txttotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtbid = new javax.swing.JTextField();
        txtcusid = new javax.swing.JTextField();
        txtnamebook = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1070, 530));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel5.setText("Book ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel7.setText("Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel8.setText("Quality");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, -1));

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel13.setText("Price");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel6.setText("Customer ID");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel12.setText("Name");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        txtnamecustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamecustomerKeyPressed(evt);
            }
        });
        jPanel1.add(txtnamecustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 150, 26));

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel14.setText("Contact No");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        txtcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontactKeyPressed(evt);
            }
        });
        jPanel1.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 150, 26));

        jLabel17.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel17.setText("Date");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        date_of_sale.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                date_of_saleKeyPressed(evt);
            }
        });
        jPanel1.add(date_of_sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 150, 26));

        txtcustomertype.setEditable(false);
        txtcustomertype.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcustomertypeKeyPressed(evt);
            }
        });
        jPanel1.add(txtcustomertype, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 150, 26));

        jLabel18.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel18.setText("Customer Type");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, -1, -1));

        cbxvip.setText("Vip");
        cbxvip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxvipMouseClicked(evt);
            }
        });
        cbxvip.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxvipKeyPressed(evt);
            }
        });
        jPanel1.add(cbxvip, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, -1, -1));

        cbxnomal.setText("Nomal");
        cbxnomal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbxnomalMouseClicked(evt);
            }
        });
        cbxnomal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxnomalActionPerformed(evt);
            }
        });
        cbxnomal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxnomalKeyPressed(evt);
            }
        });
        jPanel1.add(cbxnomal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, -1, -1));

        cmbcurrency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose one...", "Brunei", "Singapore", "Myanmar", "Lao", "India", "Philippine", "Thailand", "China", "Jappan", "Hoa Ky", "England" }));
        jPanel1.add(cmbcurrency, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 270, 26));

        txtconvert.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtconvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(txtconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 270, 26));

        lblconvert.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lblconvert.setBorder(null);
        jPanel1.add(lblconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 270, 26));

        btnconvert.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnconvert.setText("Convert");
        btnconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconvertActionPerformed(evt);
            }
        });
        jPanel1.add(btnconvert, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, -1, -1));

        btnclose.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnclose.setText("Clear");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 200, 90, -1));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel16.setText("Discount");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        btntotal.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btntotal.setText("Total");
        btntotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntotalMouseClicked(evt);
            }
        });
        btntotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btntotalKeyPressed(evt);
            }
        });
        jPanel1.add(btntotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 380, -1, -1));

        lbldiscount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lbldiscount.setBorder(null);
        lbldiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbldiscountKeyPressed(evt);
            }
        });
        jPanel1.add(lbldiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 150, 26));

        jLabel19.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        jLabel19.setText("Sub Total");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, -1, -1));

        txtsubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtsubtotal.setBorder(null);
        jPanel1.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, 150, 26));

        btnreceipt.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnreceipt.setText("Receipt");
        btnreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreceiptActionPerformed(evt);
            }
        });
        btnreceipt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnreceiptKeyPressed(evt);
            }
        });
        jPanel1.add(btnreceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 120, 50));

        jBtnDelete.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtnDelete.setText("c");
        jBtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDeleteActionPerformed(evt);
            }
        });

        jBtn10.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn10.setText("<");
        jBtn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtn10MouseClicked(evt);
            }
        });
        jBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn10ActionPerformed(evt);
            }
        });

        jBtnAddition.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtnAddition.setText("+");
        jBtnAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdditionActionPerformed(evt);
            }
        });

        jBtn14.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn14.setText("+/-");
        jBtn14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn14ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn7.setText("7");
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn8.setText("8");
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn9.setText("9");
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtnSubtraction.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtnSubtraction.setText("-");
        jBtnSubtraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSubtractionActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn4.setText("4");
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn5.setText("5");
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn6.setText("6");
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn18Multiplication.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn18Multiplication.setText("*");
        jBtn18Multiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn18MultiplicationActionPerformed(evt);
            }
        });

        jBtn1.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn1.setText("1");
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn2.setText("2");
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn3.setText("3");
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtnDivision.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtnDivision.setText("/");
        jBtnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDivisionActionPerformed(evt);
            }
        });

        jBtn0.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtn0.setText("0");
        jBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn0ActionPerformed(evt);
            }
        });

        jBtncomma.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jBtncomma.setText(".");
        jBtncomma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtncommaActionPerformed(evt);
            }
        });

        jBtnEqual.setText("=");
        jBtnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEqualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jBtn0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBtn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jBtn7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jBtncomma, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtnEqual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9)
                                        .addComponent(jBtnSubtraction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8)
                                        .addComponent(jBtn18Multiplication, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtn14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxtDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAddition, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnSubtraction, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn18Multiplication, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtncomma, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Caculator", jPanel2);

        txtbill.setColumns(20);
        txtbill.setRows(5);
        txtbillcopy.setViewportView(txtbill);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbillcopy, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtbillcopy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Receipt", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 320, 320));

        btnreset.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        btnreset.setText("Reset");
        btnreset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnresetMouseClicked(evt);
            }
        });
        btnreset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnresetKeyPressed(evt);
            }
        });
        jPanel1.add(btnreset, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 100, 40));

        txttotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txttotal.setBorder(null);
        jPanel1.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 150, 26));

        jLabel10.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setText("Bill");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, -1, -1));

        txtbid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbidKeyReleased(evt);
            }
        });
        jPanel1.add(txtbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 150, 26));

        txtcusid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcusidActionPerformed(evt);
            }
        });
        txtcusid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcusidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcusidKeyReleased(evt);
            }
        });
        jPanel1.add(txtcusid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, 26));

        txtnamebook.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamebookKeyPressed(evt);
            }
        });
        jPanel1.add(txtnamebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 150, 26));

        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpriceKeyPressed(evt);
            }
        });
        jPanel1.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 150, 26));

        txtquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtquantityKeyPressed(evt);
            }
        });
        jPanel1.add(txtquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, 26));

        btnsave.setFont(new java.awt.Font("Sitka Text", 3, 16)); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        btnsave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnsaveKeyPressed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, 100, 40));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, 340, 340));

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 180));

        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 330, 240));

        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 330, 240));

        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 330, 180));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1010, 40));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1030, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1051, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcusidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcusidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcusidActionPerformed

    private void txtbidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbidKeyReleased
        try {
            String sql = "SELECT `book_id`,`name`,`price` FROM  `addbook` WHERE `book_id`='"+txtbid.getText()+"'";
            pst = (PreparedStatement)conn.prepareStatement(sql);
            rs  = pst.executeQuery();
            if(rs.next()){
                txtbid.setText(rs.getString("book_id"));
                txtnamebook.setText(rs.getString("name"));
                txtprice.setText(rs.getString("price"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtbidKeyReleased
  
    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
      
        String bid = txtbid.getText();
        String cusid = txtcusid.getText();
        String iprice = txtprice.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String idate = sdf.format(date_of_sale.getDate() );
        String iquality = txtquantity.getText();
        String itotal = txttotal.getText();
        String idiscount = lbldiscount.getText();
              
        try {           
            String sql = "INSERT INTO `bill`(`customer_id`, `book_id`, `price`, `salequantity`,`date_of_sale`,`discount`,`total`) VALUES"
                    + " ('"+cusid+"','"+bid+"','"+iprice+"','"+iquality+"','"+idate+"','"+idiscount+"','"+itotal+"')";
            PreparedStatement pst = conn.prepareStatement(sql);          
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Successfully insert");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }    
        
    }//GEN-LAST:event_btnsaveActionPerformed

    
    private void btnreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreceiptActionPerformed

       SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String datecopy = sdf.format(date_of_sale.getDate() );
        jLabel1.setText(null);        
        
        String boobidcopy = String.valueOf(txtbid.getText());
        String namebookcopy = String.valueOf(txtnamebook.getText());
        double pricecopy = Double.parseDouble(txtprice.getText());
        double qualitycopy = Double.parseDouble(txtquantity.getText());
        String customeridcopy = String.valueOf(txtcusid.getText());
        String namecustomercopy = String.valueOf(txtnamecustomer.getText());
        String contactcopy = String.valueOf(txtcontact.getText());
        String discountcopy = String.valueOf(lbldiscount.getText());
        String totalcopy = String.valueOf(txttotal.getText());
        double subtotalcopy = Double.parseDouble(txtsubtotal.getText());
               
        
        txtbill.append("\tDALLING BOOK STORE:\n\n"
                +"Book ID:\t\t"+ boobidcopy 
                +"\nBook Name:\t\t"+namebookcopy
                +"\nPrice:\t\t "+ pricecopy
                +"\nQuality:\t\t"+ qualitycopy
                +"\n----------------------------------------------------------------------\t"
                +"\nCustomer ID:\t\t"+ customeridcopy
                +"\nCustomer Name:\t"+ namecustomercopy 
                +"\nContact No:\t\t" + contactcopy
                +"\nDate Of Sale:\t\t"+ datecopy
                +"\n----------------------------------------------------------------------\t"
                +"\nSub Total:\t\t" +subtotalcopy +"VND"
                +"\nDiscount:\t\t" + discountcopy 
                +"\n-----------------------------------------------------------------------\t"
                +"\nTOTAL:\t\t"+totalcopy +"VND"
                + "\n\n\n\nThank for coming to our book store!\n\n"
                + "\n\n\tSee you again soon!\n\n");
                        
    }//GEN-LAST:event_btnreceiptActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
       txtconvert.setText(null);
        lblconvert.setText(null);    
    }//GEN-LAST:event_btncloseActionPerformed

    
    //////////////====================Máy Tính=====================
    private void jBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn10ActionPerformed
        String backspace = null;
         if(jtxtDisplay.getText().length()> 0){
             StringBuilder strB = new StringBuilder(jtxtDisplay.getText());
             strB.deleteCharAt( jtxtDisplay.getText().length() - 1);
             backspace = strB.toString();
             jtxtDisplay.setText(backspace);
         }
    }//GEN-LAST:event_jBtn10ActionPerformed

    private void jBtn10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtn10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn10MouseClicked

    private void jBtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDeleteActionPerformed
       jtxtDisplay.setText(null);
    }//GEN-LAST:event_jBtnDeleteActionPerformed

    private void jBtn14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn14ActionPerformed
          double ops =  Double.parseDouble(String.valueOf(jtxtDisplay.getText()));
        ops = ops*(-1);
        jtxtDisplay.setText(String.valueOf(ops));
    }//GEN-LAST:event_jBtn14ActionPerformed

    private void jBtnAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdditionActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "+";
    }//GEN-LAST:event_jBtnAdditionActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
          String Enternumber = jtxtDisplay.getText() + jBtn7.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jBtn8.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
          String Enternumber = jtxtDisplay.getText() + jBtn9.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtnSubtractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSubtractionActionPerformed
         firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "-";
    }//GEN-LAST:event_jBtnSubtractionActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jBtn4.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        String Enternumber = jtxtDisplay.getText() + jBtn5.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
       String Enternumber = jtxtDisplay.getText() + jBtn6.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn18MultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn18MultiplicationActionPerformed
        firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "*";
    }//GEN-LAST:event_jBtn18MultiplicationActionPerformed

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
       String Enternumber = jtxtDisplay.getText() + jBtn1.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jBtn2.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jBtn3.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDivisionActionPerformed
         firstnum = Double.parseDouble(jtxtDisplay.getText());
        jtxtDisplay.setText("");
        operations = "/";
    }//GEN-LAST:event_jBtnDivisionActionPerformed

    private void jBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn0ActionPerformed
         String Enternumber = jtxtDisplay.getText() + jBtn0.getText();
        jtxtDisplay.setText(Enternumber);
    }//GEN-LAST:event_jBtn0ActionPerformed

    private void jBtncommaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtncommaActionPerformed
        jtxtDisplay.setText(jtxtDisplay.getText() + jBtncomma.getText());
    }//GEN-LAST:event_jBtncommaActionPerformed

    private void jBtnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEqualActionPerformed
        String answer;
        secondnum = Double.parseDouble(jtxtDisplay.getText());
        if(operations == "+"){
            result = firstnum + secondnum;
            answer  = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }else if(operations == "-"){
            result = firstnum - secondnum;
            answer  = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }else if(operations == "*"){
            result = firstnum * secondnum;
            answer  = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }else if(operations == "/"){
            result = firstnum / secondnum;
            answer  = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }else if(operations == "%"){
            result = firstnum % secondnum;
            answer  = String.format("%.2f", result);
            jtxtDisplay.setText(answer);
        }
    }//GEN-LAST:event_jBtnEqualActionPerformed

    private void btnconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconvertActionPerformed
        double VND = Double.parseDouble(txtconvert.getText());
        if(cmbcurrency.getSelectedItem().equals("Brunei")){
            String cConvert1 = String.format("$ %.2f", VND/Dollar_Brunei);
            lblconvert.setText(cConvert1);
        }if(cmbcurrency.getSelectedItem().equals("Singapore")){
            String cConvert2 = String.format("$ %.2f", VND/Dollar_Singapore);
            lblconvert.setText(cConvert2);
        }if(cmbcurrency.getSelectedItem().equals("Myanmar")){
            String cConvert3 = String.format("Ks %.2f", VND/Riel);
            lblconvert.setText(cConvert3);
        }if(cmbcurrency.getSelectedItem().equals("Lao")){
            String cConvert4 = String.format("₭ %.2f", VND/Kip);
            lblconvert.setText(cConvert4);
        }if(cmbcurrency.getSelectedItem().equals("India")){
            String cConvert5 = String.format("INR %.2f", VND/Indian_rupee);
            lblconvert.setText(cConvert5);
        }if(cmbcurrency.getSelectedItem().equals("Philippine")){
            String cConvert6 = String.format("₱ %.2f", VND/Philippine_peso);
            lblconvert.setText(cConvert6);
        }if(cmbcurrency.getSelectedItem().equals("Thailand")){
            String cConvert7 = String.format("฿ %.2f", VND/Baht);
            lblconvert.setText(cConvert7);
        }if(cmbcurrency.getSelectedItem().equals("China")){
            String cConvert8 = String.format("¥ %.2f", VND/CNY);
            lblconvert.setText(cConvert8);
        }if(cmbcurrency.getSelectedItem().equals("Jappan")){
            String cConvert9 = String.format("¥ %.2f", VND/JPY);
            lblconvert.setText(cConvert9);
        }if(cmbcurrency.getSelectedItem().equals("Hoa Ky")){
            String cConvert10= String.format("$ %.2f", VND/USD);
            lblconvert.setText(cConvert10);
        }if(cmbcurrency.getSelectedItem().equals("England")){
            String cConvert11 = String.format("	£ %.2f", VND/GBP);
            lblconvert.setText(cConvert11);
        }if(cmbcurrency.getSelectedItem().equals("Choose one...")){
            lblconvert.setText(null);
        }
    }//GEN-LAST:event_btnconvertActionPerformed

    private void cbxnomalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxnomalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxnomalActionPerformed

    private void cbxvipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxvipMouseClicked
        double VIP = 0.3;
        if(cbxvip.isSelected()){
            String Vip = String.format("%.2f", VIP);
            lbldiscount.setText(Vip);
        }else {
            lbldiscount.setText(null);
        }
    }//GEN-LAST:event_cbxvipMouseClicked

    private void cbxnomalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbxnomalMouseClicked

        double NOMAL = 0.05;
        if(cbxnomal.isSelected()){
            String Nomal = String.format("%.2f", NOMAL);
            lbldiscount.setText(Nomal);
        }else {
            lbldiscount.setText(null);
        }
    }//GEN-LAST:event_cbxnomalMouseClicked

    private void btntotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntotalMouseClicked
        double cprice = Double.parseDouble(txtprice.getText());
        double cquantity = Double.parseDouble(txtquantity.getText());
        double cdiscount = Double.parseDouble(lbldiscount.getText());
        
        double subTotal = (cprice*cquantity);
        String isubTotal = String.format("%.2f", subTotal);
        txtsubtotal.setText(isubTotal);
        
        double allTotal = subTotal-(subTotal*cdiscount);
        String iTotal = String.format("%.2f", allTotal);
        txttotal.setText(iTotal);
    }//GEN-LAST:event_btntotalMouseClicked

    private void btnresetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnresetMouseClicked
        txtbid.setText(null);
        txtnamebook.setText(null);
        txtprice.setText(null);
        txtquantity.setText(null);
        txtcusid.setText(null);
        txtnamecustomer.setText(null);
        txtcontact.setText(null);
        date_of_sale.setToolTipText(null);
        cbxvip.setText(null);
        cbxnomal.setText(null);
        lbldiscount.setText(null);
        txttotal.setText(null);
        txtsubtotal.setText(null);
    }//GEN-LAST:event_btnresetMouseClicked

    private void txtcusidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusidKeyReleased
        try {
            String sql = "SELECT `customer_id`,`name`,`contact`,`type` FROM  `addcustomer` WHERE `customer_id`='"+txtcusid.getText()+"'";
            pst = (PreparedStatement)conn.prepareStatement(sql);
            rs  = pst.executeQuery();
            if(rs.next()){
                txtcusid.setText(rs.getString("customer_id"));
                txtnamecustomer.setText(rs.getString("name"));
                txtcontact.setText(rs.getString("contact"));
                txtcustomertype.setText(rs.getString("type"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_txtcusidKeyReleased

    private void txtbidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbidKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txtnamebook.requestFocus();
        }
    }//GEN-LAST:event_txtbidKeyPressed

    private void txtnamebookKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamebookKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txtprice.requestFocus();
        }
    }//GEN-LAST:event_txtnamebookKeyPressed

    private void txtpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txtquantity.requestFocus();
        }
    }//GEN-LAST:event_txtpriceKeyPressed

    private void txtquantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquantityKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txtcusid.requestFocus();
        }
    }//GEN-LAST:event_txtquantityKeyPressed

    private void txtcusidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcusidKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txtnamecustomer.requestFocus();
        }
    }//GEN-LAST:event_txtcusidKeyPressed

    private void txtnamecustomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamecustomerKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txtcontact.requestFocus();
        }
    }//GEN-LAST:event_txtnamecustomerKeyPressed

    private void txtcontactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactKeyPressed
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            date_of_sale.requestFocus();
        }
    }//GEN-LAST:event_txtcontactKeyPressed

    private void date_of_saleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_date_of_saleKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            cbxvip.requestFocus();
        }
    }//GEN-LAST:event_date_of_saleKeyPressed

    private void txtcustomertypeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustomertypeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomertypeKeyPressed

    private void cbxvipKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxvipKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            cbxnomal.requestFocus();
        }
    }//GEN-LAST:event_cbxvipKeyPressed

    private void cbxnomalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxnomalKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            lbldiscount.requestFocus();
        }
    }//GEN-LAST:event_cbxnomalKeyPressed

    private void lbldiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbldiscountKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btntotal.requestFocus();
        }
    }//GEN-LAST:event_lbldiscountKeyPressed

    private void btnresetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnresetKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnsave.requestFocus();
        }
    }//GEN-LAST:event_btnresetKeyPressed

    private void btnsaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnsaveKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnreceipt.requestFocus();
        }
    }//GEN-LAST:event_btnsaveKeyPressed

    private void btntotalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btntotalKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnreset.requestFocus();
        }
    }//GEN-LAST:event_btntotalKeyPressed

    private void btnreceiptKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnreceiptKeyPressed

    }//GEN-LAST:event_btnreceiptKeyPressed

   
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnconvert;
    private javax.swing.JButton btnreceipt;
    private javax.swing.JButton btnreset;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btntotal;
    private javax.swing.JCheckBox cbxnomal;
    private javax.swing.JCheckBox cbxvip;
    private javax.swing.JComboBox cmbcurrency;
    private com.toedter.calendar.JDateChooser date_of_sale;
    private javax.swing.JButton jBtn0;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn10;
    private javax.swing.JButton jBtn14;
    private javax.swing.JButton jBtn18Multiplication;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jBtnAddition;
    private javax.swing.JButton jBtnDelete;
    private javax.swing.JButton jBtnDivision;
    private javax.swing.JButton jBtnEqual;
    private javax.swing.JButton jBtnSubtraction;
    private javax.swing.JButton jBtncomma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField lblconvert;
    private javax.swing.JTextField lbldiscount;
    private javax.swing.JTextField txtbid;
    private javax.swing.JTextArea txtbill;
    private javax.swing.JScrollPane txtbillcopy;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtconvert;
    private javax.swing.JTextField txtcusid;
    private javax.swing.JTextField txtcustomertype;
    private javax.swing.JTextField txtnamebook;
    private javax.swing.JTextField txtnamecustomer;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
