/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author ASUS
 */
public class LichSuBanSach extends javax.swing.JInternalFrame {

    /**
     * Creates new form BookSale
     */
    
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    
    public LichSuBanSach() {
        initComponents();
        conn = DBConnect.connect();
        tablelord();  
        
    }

    
                                                           
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblsale = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fromdate = new com.toedter.calendar.JDateChooser();
        todate = new com.toedter.calendar.JDateChooser();
        btnfilter = new javax.swing.JButton();
        btnclear = new javax.swing.JButton();
        btnprint = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1070, 530));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblsale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblsale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblsaleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblsale);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 1000, 320));

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel15.setText("From");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel16.setText("To");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 440, -1, 20));

        fromdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fromdateKeyPressed(evt);
            }
        });
        jPanel1.add(fromdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 170, 25));

        todate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                todateKeyPressed(evt);
            }
        });
        jPanel1.add(todate, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, 170, 25));

        btnfilter.setBackground(new java.awt.Color(0, 204, 204));
        btnfilter.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnfilter.setText("Filter");
        btnfilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfilterActionPerformed(evt);
            }
        });
        btnfilter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnfilterKeyPressed(evt);
            }
        });
        jPanel1.add(btnfilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        btnclear.setBackground(new java.awt.Color(0, 204, 204));
        btnclear.setFont(new java.awt.Font("Sitka Text", 1, 16)); // NOI18N
        btnclear.setText("Clear");
        btnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearActionPerformed(evt);
            }
        });
        btnclear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnclearKeyPressed(evt);
            }
        });
        jPanel1.add(btnclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 440, -1, -1));

        btnprint.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });
        jPanel1.add(btnprint, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 419, 140, 50));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Lịch Sử Bán Sách");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1020, 50));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1020, 340));

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1040, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblsaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblsaleMouseClicked
        
    }//GEN-LAST:event_tblsaleMouseClicked

    private void btnfilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfilterActionPerformed
        saleFilter();
    }//GEN-LAST:event_btnfilterActionPerformed

    private void btnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearActionPerformed
       //txtsearch.setText("");
        tablelord();
         
         SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String saleFDate = sdf.format(fromdate.getDate());
            jLabel1.setText("");                 
            String saleTDate = sdf.format(todate.getDate());
            jLabel1.setText("");
    }//GEN-LAST:event_btnclearActionPerformed

    private void fromdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fromdateKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            todate.requestFocus();
        }
    }//GEN-LAST:event_fromdateKeyPressed

    private void todateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_todateKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnfilter.requestFocus();
        }
    }//GEN-LAST:event_todateKeyPressed

    private void btnfilterKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnfilterKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnclear.requestFocus();
        }
    }//GEN-LAST:event_btnfilterKeyPressed

    private void btnclearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnclearKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnprint.requestFocus();
        }
    }//GEN-LAST:event_btnclearKeyPressed

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        int prcount=tblsale.getRowCount();
        if(prcount > 0)
        {
          DefaultTableModel tableModel=(DefaultTableModel)tblsale.getModel();
          try{
              JasperPrint jasperPrint = null;
              JasperCompileManager.compileReportToFile("C:\\Users\\DELL\\Documents\\NetBeansProjects\\BookStore\\src\\report\\LichSuBanSach.jrxml");
              jasperPrint = JasperFillManager.fillReport("C:\\Users\\DELL\\Documents\\NetBeansProjects\\BookStore\\src\\report\\LichSuBanSach.jasper", null,
              new JRTableModelDataSource(tableModel));
              JasperViewer.viewReport(jasperPrint, false);
          }catch (Exception e) {
              JOptionPane.showMessageDialog(rootPane, e);
          }
        }
        else
        {
          JOptionPane.showMessageDialog(rootPane, "Not Details to prints");
        }
    }//GEN-LAST:event_btnprintActionPerformed

            
    private void saleFilter()
        {
          SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String saleFDate = sdf.format(fromdate.getDate());
            String saleTDate = sdf.format(todate.getDate());
          if(saleFDate.length()>0 && saleTDate.isEmpty())
          {
              try {
                  String reportSql ="SELECT `book_id`, `customer_id`, `price`, `salequantity`,`date_of_sale`,`discount`,`total` FROM `bill` WHERE `date_of_sale` = '"+saleFDate+"' ";                       
                     pst = conn.prepareStatement(reportSql);
                     rs = pst.executeQuery();
                     tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));

              } catch (Exception e) {
                  JOptionPane.showMessageDialog(rootPane, "frist date");
              }
             
          }
          else if(saleFDate.length()>0 && saleTDate.length()>0)
          {
              try {
                  String reportSql ="SELECT  `book_id`, `customer_id`, `price`, `salequantity` ,`date_of_sale`,`discount`, `total` FROM `bill` WHERE  `date_of_sale` between '"+saleFDate+"' and '"+saleTDate+"'";
                     pst = conn.prepareStatement(reportSql);
                     rs = pst.executeQuery();
                     tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
                   
              } catch (Exception e) {
              }                   
          }
          else
          {
          
          JOptionPane.showMessageDialog(rootPane, "Select date to filter data");
          
          }
        }   
    
    private void tablelord()
    {
        try {
            String sql = "SELECT `book_id`, `customer_id`, `price`, `salequantity`, `date_of_sale`,`discount`,`total` FROM `bill`";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tblsale.setModel(net.proteanit.sql.DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    
                      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnclear;
    private javax.swing.JButton btnfilter;
    private javax.swing.JButton btnprint;
    private com.toedter.calendar.JDateChooser fromdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblsale;
    private com.toedter.calendar.JDateChooser todate;
    // End of variables declaration//GEN-END:variables
}
