package Interface;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ASUS
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Login() {
        initComponents();
        conn = DBConnect.connect();
        
        
        //create a border for the create account 
        Border lblBorder_register = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.gray);
        lblregister.setBorder(lblBorder_register);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtuname = new javax.swing.JTextField();
        txtpword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblregister = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, -1));

        txtuname.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        txtuname.setText("username");
        txtuname.setToolTipText("");
        txtuname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtunameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtunameFocusLost(evt);
            }
        });
        txtuname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtunameKeyPressed(evt);
            }
        });
        jPanel1.add(txtuname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 200, 30));

        txtpword.setText("password");
        txtpword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtpwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtpwordFocusLost(evt);
            }
        });
        txtpword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpwordKeyPressed(evt);
            }
        });
        jPanel1.add(txtpword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 200, 30));

        btnLogin.setBackground(new java.awt.Color(255, 51, 51));
        btnLogin.setText("Login");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 70, -1));

        btnCancel.setBackground(new java.awt.Color(0, 0, 255));
        btnCancel.setText("cancel");
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        btnCancel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnCancelKeyPressed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 70, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Welcome");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 160, -1));

        lblregister.setForeground(new java.awt.Color(255, 0, 51));
        lblregister.setText("No Account? Sign up now");
        lblregister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblregister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblregisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblregisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblregisterMouseExited(evt);
            }
        });
        jPanel1.add(lblregister, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    //buton cancel
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        System.exit(WIDTH);
    }//GEN-LAST:event_btnCancelActionPerformed

    //login
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       
        
        String uname = txtuname.getText();
        String pword = String.valueOf(txtpword.getPassword());
        
        //show a message if Username or Password fields empty
        if(uname.trim().equals("username")){
            JOptionPane.showMessageDialog(null, "Enter your Username","Empty Username",2);
        }else if(pword.trim().equals("password")){
            JOptionPane.showMessageDialog(null, "Enter your Password","Empty Password",2);
        }else{
            try {
            String sql = "SELECT * FROM `login` WHERE `username` = ? AND `password` = ?";
            //PreparedStatement pst = conn.prepareStatement(sql);
            //pst.execute();
            pst = (PreparedStatement)conn.prepareStatement(sql);
            
            pst.setString(1, uname);
            pst.setString(2, pword);
            rs  = pst.executeQuery();
            
            if(rs.next())
            {
                Home ho = new Home();
                ho.setVisible(true);
                ho.pack();;
                ho.setLocationRelativeTo(null);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "username or password incorrect","Login Error",2);
            }
            

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        }
        
        
        /*if(uname.equals("admin")&& pword.equals("1234")){
        Home ho = new Home();
        ho.setVisible(true);
        this.dispose();
        }
        else {
                JOptionPane.showMessageDialog(rootPane, "user or password incorrect");
        }*/
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtunameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtunameFocusGained
        if(txtuname.getText().trim().toLowerCase().equals("username")){
            txtuname.setText("");
        }
    }//GEN-LAST:event_txtunameFocusGained

    private void txtunameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtunameFocusLost
        if(txtuname.getText().trim().equals("")|| txtuname.getText().trim().toLowerCase().equals("username")){
            txtuname.setText("username");
        }
    }//GEN-LAST:event_txtunameFocusLost

    private void txtpwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpwordFocusGained
       String pass = String.valueOf(txtpword.getPassword());
       
        if(pass.trim().toLowerCase().equals("password")){
            txtpword.setText("");
        }
    }//GEN-LAST:event_txtpwordFocusGained

    private void txtpwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtpwordFocusLost
        String pass = String.valueOf(txtpword.getPassword());
        
        if(pass.trim().equals("")|| pass.trim().toLowerCase().equals("password")){
            txtpword.setText("password");
        }
    }//GEN-LAST:event_txtpwordFocusLost

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
       btnLogin.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_btnLoginMouseExited

    private void lblregisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregisterMouseEntered
        Border lblBorder_register = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.red);
        lblregister.setBorder(lblBorder_register);
    }//GEN-LAST:event_lblregisterMouseEntered

    private void lblregisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregisterMouseExited
        Border lblBorder_register = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        lblregister.setBorder(lblBorder_register);
    }//GEN-LAST:event_lblregisterMouseExited

    private void txtunameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtunameKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txtpword.requestFocus();
        }
    }//GEN-LAST:event_txtunameKeyPressed

    private void txtpwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpwordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnLogin.requestFocus();
        }
    }//GEN-LAST:event_txtpwordKeyPressed

    private void btnCancelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnCancelKeyPressed

    }//GEN-LAST:event_btnCancelKeyPressed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed
       if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnCancel.requestFocus();
        }
    }//GEN-LAST:event_btnLoginKeyPressed

    private void lblregisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblregisterMouseClicked
       Register_Form rf = new Register_Form();
       rf.setVisible(true);
       rf.pack();
       rf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_lblregisterMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
       btnCancel.setBackground(new Color(102,102,102));
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
       btnCancel.setBackground(new Color(0,0,255));
    }//GEN-LAST:event_btnCancelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblregister;
    private javax.swing.JPasswordField txtpword;
    private javax.swing.JTextField txtuname;
    // End of variables declaration//GEN-END:variables
}
