package Interface;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
/**
 *
 * @author ASUS
 */
public class Register_Form extends javax.swing.JFrame {

    /**
     * Creates new form Register_Form
     */
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public Register_Form() {
        initComponents();
        conn = DBConnect.connect();
        this.setLocationRelativeTo(null);
        
        
        //create a border for the create account 
        Border lblBorder_login_back = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.gray);
        lbllogin_back.setBorder(lblBorder_login_back);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public boolean verifyFields()
    {
       String yemail = txtEmail.getText();
       String yname = txtName.getText();
       String pass = String.valueOf(pwfpass.getPassword());
       String cpass = String.valueOf(pwfconfirmpassword.getPassword());
       
       //check empty fields
       if(yemail.trim().equals("") || yname.trim().equals("") || pass.trim().equals("") || cpass.trim().equals("")){
           JOptionPane.showMessageDialog(null, "One or more fields are empty","Empty Fields",2);
           return false;
       }
       
       //check if the two password are equals
       else if(!pass.equals(cpass)){
           JOptionPane.showMessageDialog(null, "Password doesn't match","Confirm password",2);
           return false;
       }
       
       //if everything is ok
       else {
           return true;
       }
    }
    
    //create a function to check if the entred username already exists in the database
    public boolean checkUsername(String username){
        PreparedStatement pst;
        ResultSet rs;
        boolean username_exist = false;
        
        Connection conn = DBConnect.connect();
        String sql ="SELECT * FROM `login` WHERE `username` = ? ";
        try {
            pst = (PreparedStatement)conn.prepareStatement(sql);
            pst.setString(1, username);
            rs  = pst.executeQuery();
            
            if(rs.next()){
                username_exist = true;
                JOptionPane.showMessageDialog(null,"This Username is Already Taken, Choose Another One","Username Failed", 2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
        return username_exist;
    }
    
    
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        lbllogin_back = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxagree = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        pwfpass = new javax.swing.JPasswordField();
        pwfconfirmpassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(0, 153, 0));
        btnLogin.setText("Register");
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLoginMouseExited(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 250, 40));

        jLabel4.setBackground(new java.awt.Color(0, 51, 255));
        jLabel4.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Register");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 160, -1));

        txtEmail.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        txtEmail.setText("email");
        txtEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtEmailFocusLost(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmailKeyPressed(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 250, 30));

        txtName.setFont(new java.awt.Font("Sitka Text", 0, 11)); // NOI18N
        txtName.setText("username");
        txtName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNameFocusLost(evt);
            }
        });
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
        });
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 250, 30));

        lbllogin_back.setForeground(new java.awt.Color(0, 204, 0));
        lbllogin_back.setText("Already Have An Account? Login ");
        lbllogin_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbllogin_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbllogin_backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbllogin_backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbllogin_backMouseExited(evt);
            }
        });
        jPanel1.add(lbllogin_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel2.setText("Your Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel3.setText("UserName");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 20));

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel6.setText("Confirm Password");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        cbxagree.setForeground(new java.awt.Color(255, 255, 255));
        cbxagree.setText("I accept the Terms of Use & Privacy Policy ");
        cbxagree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxagreeKeyPressed(evt);
            }
        });
        jPanel1.add(cbxagree, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 250, 20));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Create your account. It's free and only takes a minute.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 350, -1));

        pwfpass.setText("password");
        pwfpass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwfpassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwfpassFocusLost(evt);
            }
        });
        pwfpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwfpassKeyPressed(evt);
            }
        });
        jPanel1.add(pwfpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 250, 30));

        pwfconfirmpassword.setText("password");
        pwfconfirmpassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pwfconfirmpasswordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pwfconfirmpasswordFocusLost(evt);
            }
        });
        pwfconfirmpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwfconfirmpasswordActionPerformed(evt);
            }
        });
        pwfconfirmpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pwfconfirmpasswordKeyPressed(evt);
            }
        });
        jPanel1.add(pwfconfirmpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 250, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/1.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseEntered
        btnLogin.setBackground(new Color(255,51,51));
    }//GEN-LAST:event_btnLoginMouseEntered

    private void btnLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseExited
        btnLogin.setBackground(new Color(0,153,0));
    }//GEN-LAST:event_btnLoginMouseExited

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String username = txtName.getText();
        String email = txtEmail.getText();
        String pass = String.valueOf(pwfpass.getPassword());
        String cpass = String.valueOf(pwfconfirmpassword.getPassword());
        
        if(verifyFields())
        {
            PreparedStatement pst;
            ResultSet rs;
            String sql = "INSERT INTO `login`( `username`, `email`, `password`) VALUES (?,?,?)";
            
            if(email.trim().equals("email")){
                JOptionPane.showMessageDialog(null, "Enter your Email","Empty Email",2);
            }else if(username.trim().equals("username")){
                JOptionPane.showMessageDialog(null, "Enter your Username","Empty Username",2);
            }else if(pass.trim().equals("password")){
                JOptionPane.showMessageDialog(null, "Enter your Password","Empty Password",2);
            }else if(cpass.trim().equals("password")){
                JOptionPane.showMessageDialog(null, "Enter your Confirm Password","Empty Confirm Password",2);
            }else if(!cbxagree.isSelected()){
                JOptionPane.showMessageDialog(null, "Acceipt Policy","Policy doesn't confirm",2);
            }else{
                String emailPattern = "^[\\w!#$%&’*+/=?`{|}~^-]+(?:\\.[\\w!#$%&’*+/=?`{|}~^-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$";
                Pattern regex = Pattern.compile(emailPattern);
                Matcher matcher = regex.matcher(email);
                if (matcher.find()){
                    try {
                        pst = (PreparedStatement)conn.prepareStatement(sql);
                         pst.setString(1,username);
                         pst.setString(2, email);
                         pst.setString(3, pass);

                         try {
                            if(pst.executeUpdate() != 0){
                                JOptionPane.showMessageDialog(null, "Your Account Has Been Created");
                            }
                            else{
                                JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                            }
                        } catch (Exception e) {                           
                        }
                    } catch (SQLException ex) {
                        Logger.getLogger(Register_Form.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Email khong hop le!!");
                    txtEmail.setText("");
                }                                  
            }
        }                  
    }//GEN-LAST:event_btnLoginActionPerformed

    
    
    private void lbllogin_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogin_backMouseClicked
        Login lf = new Login();
        lf.setVisible(true);
        lf.pack();
        lf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbllogin_backMouseClicked

    private void lbllogin_backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogin_backMouseEntered
        Border lblBorder_register = BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(0,204,0));
        lbllogin_back.setBorder(lblBorder_register);
    }//GEN-LAST:event_lbllogin_backMouseEntered

    private void lbllogin_backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbllogin_backMouseExited
        Border lblBorder_register = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.lightGray);
        lbllogin_back.setBorder(lblBorder_register);
    }//GEN-LAST:event_lbllogin_backMouseExited

    private void txtEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            txtName.requestFocus();
        }
    }//GEN-LAST:event_txtEmailKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            pwfpass.requestFocus();
        }
    }//GEN-LAST:event_txtNameKeyPressed

    private void pwfpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwfpassKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            pwfconfirmpassword.requestFocus();
        }
    }//GEN-LAST:event_pwfpassKeyPressed

    private void pwfconfirmpasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pwfconfirmpasswordKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            cbxagree.requestFocus();
        }
    }//GEN-LAST:event_pwfconfirmpasswordKeyPressed

    private void cbxagreeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxagreeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            btnLogin.requestFocus();
        }
    }//GEN-LAST:event_cbxagreeKeyPressed

    private void txtEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusGained
       if(txtEmail.getText().trim().toLowerCase().equals("email")){
            txtEmail.setText("");
        }
    }//GEN-LAST:event_txtEmailFocusGained

    private void txtEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmailFocusLost
        if(txtEmail.getText().trim().equals("")|| txtEmail.getText().trim().toLowerCase().equals("email")){
            txtEmail.setText("email");
        }
    }//GEN-LAST:event_txtEmailFocusLost

    private void txtNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusGained
        if(txtName.getText().trim().toLowerCase().equals("username")){
            txtName.setText("");
        }
    }//GEN-LAST:event_txtNameFocusGained

    private void txtNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNameFocusLost
        if(txtName.getText().trim().equals("")|| txtName.getText().trim().toLowerCase().equals("username")){
            txtName.setText("username");
        }
    }//GEN-LAST:event_txtNameFocusLost

    private void pwfpassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfpassFocusGained
        String pass = String.valueOf(pwfpass.getPassword());
       
        if(pass.trim().toLowerCase().equals("password")){
            pwfpass.setText("");
        }
    }//GEN-LAST:event_pwfpassFocusGained

    private void pwfpassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfpassFocusLost
        String pass = String.valueOf(pwfpass.getPassword());
        
        if(pass.trim().equals("")|| pass.trim().toLowerCase().equals("password")){
            pwfpass.setText("password");
        }
    }//GEN-LAST:event_pwfpassFocusLost

    private void pwfconfirmpasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfconfirmpasswordFocusGained
        String cpass = String.valueOf(pwfconfirmpassword.getPassword());
       
        if(cpass.trim().toLowerCase().equals("password")){
            pwfconfirmpassword.setText("");
        }
    }//GEN-LAST:event_pwfconfirmpasswordFocusGained

    private void pwfconfirmpasswordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pwfconfirmpasswordFocusLost
        String cpass = String.valueOf(pwfconfirmpassword.getPassword());
        
        if(cpass.trim().equals("")|| cpass.trim().toLowerCase().equals("password")){
            pwfconfirmpassword.setText("password");
        }
    }//GEN-LAST:event_pwfconfirmpasswordFocusLost

    private void pwfconfirmpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwfconfirmpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwfconfirmpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JCheckBox cbxagree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbllogin_back;
    private javax.swing.JPasswordField pwfconfirmpassword;
    private javax.swing.JPasswordField pwfpass;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
